In [1]:
from kaggle_environments import make
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()
import matplotlib.pyplot as plt

Loading environment football failed: No module named 'gfootball'


In [2]:
from lux.game import Game
from base_action import MapState, GameState

game_state = None

def agent(observation, configuration):
    
    global game_state

    ### Do not edit ###
    if observation["step"] == 0:
        game_state = Game()
        game_state._initialize(observation["updates"])
        game_state._update(observation["updates"][2:])
        game_state.id = observation.player
    else:
        game_state._update(observation["updates"])
    
    ### Bot code ###
    actions = []
    
    if game_state.turn == 0:
        actions.append(annotate.circle(0, 0))
  
    return actions

In [3]:
env = make('lux_ai_2021', configuration={
    'seed': 123456789, 
    'loglevel': 0, 
    'annotations': False, 
    'episodeSteps': 2,
}, debug=False)

In [4]:
steps = env.run([agent, 'simple_agent'])

In [5]:
current_game_state = GameState(game_state)
current_game_state.get_day_or_night()
current_game_state.get_game_state()

array([ 16,  16,   0,   0,   1,   1,   0,   1, 104], dtype=int8)

In [6]:
map_state = MapState(game_state)

In [7]:
map_state.set_map_state()
map_state.game_state_massive.shape

(16, 16, 21)

In [8]:
map_state.game_state_massive[1, 1]

array([  1.,   1., 387.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
      dtype=float16)

In [9]:
map_state.game_state_massive

array([[[  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        ...,
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       [[  1.,   1., 331., ...,   0.,   0.,   0.],
        [  1.,   1., 387., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        ...,
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  1.,   1., 387., ...,   0.,   0.,   0.],
        [  1.,   1., 331., ...,   0.,   0.,   0.]],

       [[  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        ...,
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.],
        [  0.,   0.,   0., ...,   0.,   0.,   0.]],

       ...,

       [[  0.,   0.,   0